import WebSocket from "ws";
import OpenAI from "openai";

//
const openai = new OpenAI({
    organization: "YOUR_ORG_ID",
    project: "$PROJECT_ID",
});

//Grab bot user id
const BOT_USER_ID = '';
//Grab O Authentication token. Needs scopes user:bot, user:read:chat, user:write:chat
const OAUTHTOKEN = '';
//Grab Client ID
const CLIENT_ID = '';

//Grab chat channel user id
const chat_channel_user_id = '';

//Used to start the websocket client
const EVENTSUB_WEBSOCKET_URL = 'wss://eventsub.wss.twitch.tv/ws';

var WebSocketSessionID;

(async () => {
    
    //Verifies if authentication is valid before proceeding with the program
    await getAuth();

    //If verification is correct, start the client.
    const websocketClient = startWebSocketClient();

}) ();


//Program will continue to run unless closed forcefully. TODO: Write a function for the CLI that closes the program.

async function getAuth() {
	// https://dev.twitch.tv/docs/authentication/validate-tokens/#how-to-validate-a-token
	let response = await fetch('https://id.twitch.tv/oauth2/validate', {
		method: 'GET',
		headers: {
			'Authorization': 'OAuth ' + OAUTH_TOKEN
		}
	});

    //Checks to see if authentication is valid.
	if (response.status != 200) {
		let data = await response.json();
		console.error("Token is not valid. /oauth2/validate returned status code " + response.status);
		console.error(data);
		process.exit(1);
	}

	console.log("Validated token.");
}

function startWebSocketClient() {
	let websocketClient = new WebSocket(EVENTSUB_WEBSOCKET_URL);

	websocketClient.on('error', console.error);

	websocketClient.on('open', () => {
		console.log('WebSocket connection opened to ' + EVENTSUB_WEBSOCKET_URL);
	});

	websocketClient.on('message', (data) => {
		handleWebSocketMessage(JSON.parse(data.toString()));
	});

	return websocketClient;
}

function handleWebSocketMessage(data) {
	switch (data.metadata.message_type) {
		case 'session_welcome': // First message you get from the WebSocket server when connecting
			websocketSessionID = data.payload.session.id; // Register the Session ID it gives us

			// Listen to EventSub, which joins the chatroom from your bot's account
			registerEventSubListeners();
			break;
		case 'notification': // An EventSub notification has occurred, such as channel.chat.message
			switch (data.metadata.subscription_type) {
				case 'channel.chat.message':
					// First, print the message to the program's console.
					console.log(`MSG #${data.payload.event.broadcaster_user_login} <${data.payload.event.chatter_user_login}> ${data.payload.event.message.text}`);

					// Then check to see if that message was "HeyGuys"
					if (data.payload.event.message.text.trim() == "HeyGuys") {
						// If so, send back "VoHiYo" to the chatroom
						sendChatMessage("VoHiYo")
					}

					break;
			}
			break;
	}
}

async function sendChatMessage(chatMessage) {
	let response = await fetch('https://api.twitch.tv/helix/chat/messages', {
		method: 'POST',
		headers: {
			'Authorization': 'Bearer ' + OAUTH_TOKEN,
			'Client-Id': CLIENT_ID,
			'Content-Type': 'application/json'
		},
		body: JSON.stringify({
			broadcaster_id: CHAT_CHANNEL_USER_ID,
			sender_id: BOT_USER_ID,
			message: chatMessage
		})
	});

    const completion = await openai.chat.completions.create({
        messages: [
            {"role": "system", "content": "You are a helpful assistant for a group of people."},
            //TODO: The user should pull it's content from a json file generated by twitch API
            {"role": "user", "content": chatMessage}
          ],
        model: "gpt-4o-mini",
      });
    
      console.log(completion.choices[0]);
	if (response.status != 200) {
		let data = await response.json();
		console.error("Failed to send chat message");
		console.error(data);
	} else {
		console.log("Sent chat message: " + chatMessage);
	}
}

async function main() {
    const completion = await openai.chat.completions.create({
      messages: [
          {"role": "system", "content": "You are a helpful assistant."},
          //TODO: The user should pull it's content from a json file generated by twitch API
          {"role": "user", "content": "What is a LLM?"}
        ],
      model: "gpt-4o-mini",
    });
  
    console.log(completion.choices[0]);
  }
  main();